--
-- Baseline schema for OpenMicHub.
--
-- Taken from the schema Hibernate had been generating with ddl-auto: update, so
-- an existing database and a fresh one converge on the same shape. From here on
-- the schema is owned by these migration files; Hibernate only validates that
-- its entity mappings still match.
--
-- Not included, deliberately:
--
--   artist_embedding, and the pgvector extension it needs, are created and
--   owned by ml_service. That service is deployable on its own and its table is
--   meaningless to the API, so it manages its own DDL idempotently rather than
--   waiting on a migration here.
--

CREATE TABLE public.artist_availability (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    day_of_week character varying(255),
    artist_id bigint,
    CONSTRAINT artist_availability_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);

CREATE SEQUENCE public.artist_availability_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.artist_unavailability (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    end_date date NOT NULL,
    reason character varying(255),
    start_date date NOT NULL,
    artist_id bigint NOT NULL
);

ALTER TABLE public.artist_unavailability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artist_unavailability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.artists (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    bio character varying(255),
    hourly_rate double precision NOT NULL,
    rating double precision,
    stage_name character varying(255) NOT NULL,
    user_id bigint
);

CREATE TABLE public.artists_genres (
    artist_id bigint NOT NULL,
    genres_id bigint NOT NULL
);

ALTER TABLE public.artists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.availability_time (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    end_time time(6) without time zone NOT NULL,
    start_time time(6) without time zone NOT NULL,
    availability_id bigint
);

CREATE SEQUENCE public.availability_time_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.booking (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    end_time time(6) without time zone NOT NULL,
    event_date date NOT NULL,
    event_type character varying(255) NOT NULL,
    start_time time(6) without time zone NOT NULL,
    status character varying(255),
    total_amount double precision NOT NULL,
    venue character varying(255) NOT NULL,
    artist_id bigint,
    user_id bigint,
    CONSTRAINT booking_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'DECLINED'::character varying, 'NO_SHOW'::character varying])::text[])))
);

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.category (
    id bigint NOT NULL,
    active boolean NOT NULL,
    description character varying(255),
    name character varying(255)
);

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chats (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    content character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    recipient_id bigint NOT NULL,
    sender_id bigint NOT NULL
);

ALTER TABLE public.chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.genre (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    active boolean NOT NULL,
    description character varying(255),
    name character varying(255),
    slug character varying(255)
);

CREATE TABLE public.genre_categories (
    genre_id bigint NOT NULL,
    categories_id bigint NOT NULL
);

ALTER TABLE public.genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.otp (
    id bigint NOT NULL,
    expiry_time timestamp(6) without time zone,
    is_used boolean,
    otp_value character varying(255) NOT NULL,
    purpose character varying(255),
    user_id bigint,
    CONSTRAINT otp_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['REGISTER'::character varying, 'FORGOT_PASSWORD'::character varying, 'CHANGE_EMAIL'::character varying])::text[])))
);

ALTER TABLE public.otp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payment (
    payment_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    payment_method character varying(255),
    payment_status character varying(255),
    payment_time time(6) without time zone,
    payment_type character varying(255),
    pidx character varying(255),
    product_code character varying(255),
    received_amount double precision NOT NULL,
    system_charges double precision NOT NULL,
    total_amount double precision NOT NULL,
    transaction_code character varying(255),
    transaction_id character varying(255),
    booking_id bigint,
    user_info_entity_id bigint,
    CONSTRAINT payment_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'ABORTED'::character varying])::text[]))),
    CONSTRAINT payment_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['PARTIAL'::character varying, 'FULL'::character varying, 'WITHDRAW'::character varying])::text[])))
);

ALTER TABLE public.payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_like (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    is_liked boolean,
    post_id bigint,
    user_id bigint
);

ALTER TABLE public.post_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.posts (
    post_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    content text,
    likes_count integer,
    title character varying(255),
    artist_id bigint
);

CREATE TABLE public.posts_images (
    posts_post_id bigint NOT NULL,
    images character varying(255)
);

ALTER TABLE public.posts ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.review (
    review_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    comment character varying(255),
    rating integer NOT NULL,
    artist_id bigint NOT NULL,
    booking_id bigint NOT NULL,
    reviewer_id bigint NOT NULL
);

ALTER TABLE public.review ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.roles (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255) NOT NULL
);

CREATE SEQUENCE public.roles_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.transaction (
    transaction_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    amount double precision,
    booking_id bigint,
    status character varying(255),
    transaction_purpose character varying(255),
    transaction_type character varying(255),
    virtual_coin_virtual_coin_id bigint,
    CONSTRAINT transaction_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'DECLINED'::character varying])::text[]))),
    CONSTRAINT transaction_transaction_purpose_check CHECK (((transaction_purpose)::text = ANY ((ARRAY['BOOKING_PAYMENT'::character varying, 'WITHDRAWAL_REQUEST'::character varying, 'SERVICE_FEE'::character varying, 'ALL'::character varying])::text[]))),
    CONSTRAINT transaction_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying, 'ALL'::character varying])::text[])))
);

ALTER TABLE public.transaction ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    location character varying(255),
    password character varying(255) NOT NULL,
    phone_number character varying(255),
    profile character varying(255),
    is_verified boolean NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users_roles (
    user_entity_id bigint NOT NULL,
    roles_id bigint NOT NULL
);

CREATE TABLE public.virtual_coin (
    virtual_coin_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    balance double precision,
    artist_id bigint
);

ALTER TABLE public.virtual_coin ALTER COLUMN virtual_coin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.virtual_coin_virtual_coin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.artist_availability
    ADD CONSTRAINT artist_availability_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.artist_unavailability
    ADD CONSTRAINT artist_unavailability_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT artists_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.availability_time
    ADD CONSTRAINT availability_time_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.otp
    ADD CONSTRAINT otp_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (payment_id);

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT post_like_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (post_id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (review_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id);

ALTER TABLE ONLY public.otp
    ADD CONSTRAINT uk3pv0kmf7myhyxr6q8pbagxvpt UNIQUE (otp_value);

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT uk3tcwv992nnpibrerhhl7nnjfb UNIQUE (stage_name);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);

ALTER TABLE ONLY public.genre_categories
    ADD CONSTRAINT ukmyak81vrd5mfjwcgi49onbcp1 UNIQUE (categories_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT ukpk6mjiy6a6er537l9ut4hyolk UNIQUE (user_id);

ALTER TABLE ONLY public.virtual_coin
    ADD CONSTRAINT ukpmc4o7xk2ug0wit3wqdhdtqh9 UNIQUE (artist_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.virtual_coin
    ADD CONSTRAINT virtual_coin_pkey PRIMARY KEY (virtual_coin_id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk29sgaw0fsbkrgfd8gv15j9vvk FOREIGN KEY (reviewer_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.availability_time
    ADD CONSTRAINT fk2ybybctceibnfw4nq0y92gawq FOREIGN KEY (availability_id) REFERENCES public.artist_availability(id);

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk3olbjqqn5ioxavgftg0vex7im FOREIGN KEY (virtual_coin_virtual_coin_id) REFERENCES public.virtual_coin(virtual_coin_id);

ALTER TABLE ONLY public.genre_categories
    ADD CONSTRAINT fk48vnym00t3b6ovh7syg7rtwjb FOREIGN KEY (genre_id) REFERENCES public.genre(id);

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT fk66qywv3f3xheb6sk2vxu6vftb FOREIGN KEY (recipient_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT fk6nh88dso8f1xjofmrwy0bf7qf FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.artists_genres
    ADD CONSTRAINT fk7ta2fad2036m8b7n09geqviir FOREIGN KEY (genres_id) REFERENCES public.category(id);

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk7udbel7q86k041591kj6lfmvw FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk7v417qhe0i2m9h8njggvciv00 FOREIGN KEY (user_entity_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.artists_genres
    ADD CONSTRAINT fk9anvv9h9yw5qiye0p2ws9qofk FOREIGN KEY (artist_id) REFERENCES public.artists(id);

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fka62j07k5mhgifpp955h37ponj FOREIGN KEY (roles_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.virtual_coin
    ADD CONSTRAINT fkb0a0svoqi2ojf8u5ou34v8u7s FOREIGN KEY (artist_id) REFERENCES public.artists(id);

ALTER TABLE ONLY public.artist_unavailability
    ADD CONSTRAINT fkbrdalmrsiw7qlf6r96yywlx85 FOREIGN KEY (artist_id) REFERENCES public.artists(id);

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkh95plgqvsb15mpwwt6sji2f33 FOREIGN KEY (artist_id) REFERENCES public.artists(id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkhv2gay8t3diuxb0ygog34duld FOREIGN KEY (artist_id) REFERENCES public.artists(id);

ALTER TABLE ONLY public.posts_images
    ADD CONSTRAINT fkjcfikn0jum8hmkmjbnv2w74jy FOREIGN KEY (posts_post_id) REFERENCES public.posts(post_id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkk4xawqohtguy5yx5nnpba6yf3 FOREIGN KEY (booking_id) REFERENCES public.booking(id);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkk66mo7q0lphq9qddp1ogl2cge FOREIGN KEY (user_info_entity_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT fkla7peq6fislsxok7a4wxv5p36 FOREIGN KEY (sender_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.artist_availability
    ADD CONSTRAINT fkojop20b9436uvf95eu542911g FOREIGN KEY (artist_id) REFERENCES public.artists(id);

ALTER TABLE ONLY public.genre_categories
    ADD CONSTRAINT fkotb77cp5as4hsih4coqmbgyeu FOREIGN KEY (categories_id) REFERENCES public.category(id);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkqewrl4xrv9eiad6eab3aoja65 FOREIGN KEY (booking_id) REFERENCES public.booking(id);

ALTER TABLE ONLY public.otp
    ADD CONSTRAINT fks0hlsjury48cekfbfusk11lyr FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fktl5iiqqbv99rhpr2bhqy1v6cw FOREIGN KEY (artist_id) REFERENCES public.artists(id);
